name: Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        entry:
          - { os: 'ubuntu-latest', python-version: "3.9" }
          - { os: 'ubuntu-latest', python-version: "3.10" }
          - { os: 'ubuntu-latest', python-version: "3.11" }
          - { os: 'macos-latest', python-version: "3.11" }
          - { os: 'windows-latest', python-version: "3.11" }
          - { os: 'ubuntu-latest', python-version: "3.12" }
          - { os: 'macos-latest', python-version: "3.12" }
          - { os: 'windows-latest', python-version: "3.12" }
          
    name: test (os=${{ matrix.entry.os }}, python=${{ matrix.entry.python-version }})
    continue-on-error: ${{ matrix.entry.experimental || false }}
    runs-on: ${{ matrix.entry.os }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Set Up Python - ${{ matrix.entry.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.entry.python-version }}
        env:
          PIP_NO_PYTHON_VERSION_WARNING: 1
          PIP_DISABLE_PIP_VERSION_CHECK: 1
      - name: Install Dependencies
        run: |
          python -m pip install nox
      - name: Run Tests
        run: |
          python -m nox -rs test-${{ matrix.entry.python-version }}
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: ./junit/opensearch-py-codecov.xml
