name: Unified Release

on: [push, pull_request]

jobs:
  assemble:
    name: Assemble
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack_version: ['2.6.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: "./.ci/make.sh assemble ${{ matrix.stack_version }}"
        name: Assemble ${{ matrix.stack_version }}
